// lib/utils/mock_data.dart

class MockData {
  static const String userName = "Ravi";
  static const double portfolioValue = 125000.00;
  static const double totalInvestment = 100000.00;
  static const double todayChange = 2500.00;
  static const bool isProfit = true;
  static const double goldGrams = 20.5;
  static const double silverGrams = 150.0;
  static const int goldPricePerGram = 6245;
  static const int goldPriceChange = 45; // positive = increase
  static const double goldValue = 128022.50; // goldGrams * goldPricePerGram
  static const int silverPricePerGram = 78;
  static const int silverPriceChange = 2; // positive = increase
  static const double silverValue = 11700.00; // silverGrams * silverPricePerGram
  static const double goldChangePercent = 2.1;
  static const double silverChangePercent = 1.5;

  // Gold scheme breakdown
  static const List<Map<String, dynamic>> goldSchemes = [
    {
      'name': 'Gold Scheme A',
      'grams': 10.5,
      'value': 65572.50,
    },
    {
      'name': 'Gold Scheme B',
      'grams': 10.0,
      'value': 62450.00,
    },
  ];

  // Silver scheme breakdown
  static const List<Map<String, dynamic>> silverSchemes = [
    {
      'name': 'Silver Scheme A',
      'grams': 80.0,
      'value': 6240.00,
    },
    {
      'name': 'Silver Scheme B',
      'grams': 70.0,
      'value': 5460.00,
    },
  ];
  static const String nextInstallmentDate = "5 Dec 2024";
  static const double nextInstallmentAmount = 5000.00;
  static const double overallReturnPercent = 25.0;

  static const List<Map<String, dynamic>> recentPayments = [
    {
      'date': '25 Nov 2024',
      'amount': 5000.00,
      'status': 'Completed',
      'method': 'UPI',
      'scheme': 'Monthly Gold Plan',
    },
    {
      'date': '18 Nov 2024',
      'amount': 5000.00,
      'status': 'Completed',
      'method': 'Bank Transfer',
      'scheme': 'Monthly Gold Plan',
    },
  ];

  // Active schemes for user
  static const List<Map<String, dynamic>> activeSchemes = [
    {
      'schemeId': 'INV-001',
      'schemeName': 'Gold Scheme A',
      'frequency': 'daily', // daily | weekly | monthly
      'installmentAmount': 500,
      'startDate': '2024-11-01',
      'totalInstallments': 200,
      'paidInstallments': 25,
      'nextDueDate': '2024-11-30',
    },
  ];

  // Next 5 upcoming payment dates for dashboard preview
  // Order: Today (DUE), Yesterday (PAID), 2 days ago (PAID), 3 days ago (MISSED), 4 days ago (PAID)
  static List<Map<String, dynamic>> get paymentCalendarPreview {
    final today = DateTime.now();
    final yesterday = today.subtract(const Duration(days: 1));
    final twoDaysAgo = today.subtract(const Duration(days: 2));
    final threeDaysAgo = today.subtract(const Duration(days: 3));
    final fourDaysAgo = today.subtract(const Duration(days: 4));
    
    return [
      {
        'date': today,
        'dayNum': today.day.toString(),
        'dayName': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][today.weekday - 1],
        'status': 'DUE', // Current date shows as DUE
        'schemeName': 'Gold Scheme A',
        'amount': 500,
      },
      {
        'date': yesterday,
        'dayNum': yesterday.day.toString(),
        'dayName': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][yesterday.weekday - 1],
        'status': 'PAID',
        'schemeName': 'Gold Scheme A',
        'amount': 500,
      },
      {
        'date': twoDaysAgo,
        'dayNum': twoDaysAgo.day.toString(),
        'dayName': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][twoDaysAgo.weekday - 1],
        'status': 'PAID',
        'schemeName': 'Gold Scheme A',
        'amount': 500,
      },
      {
        'date': threeDaysAgo,
        'dayNum': threeDaysAgo.day.toString(),
        'dayName': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][threeDaysAgo.weekday - 1],
        'status': 'MISSED',
        'schemeName': 'Gold Scheme A',
        'amount': 500,
      },
      {
        'date': fourDaysAgo,
        'dayNum': fourDaysAgo.day.toString(),
        'dayName': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][fourDaysAgo.weekday - 1],
        'status': 'PAID',
        'schemeName': 'Gold Scheme A',
        'amount': 500,
      },
    ];
  }

  // Full payment schedule for Payment Schedule screen
  static List<Map<String, dynamic>> get paymentSchedule {
    final today = DateTime.now();
    final upcoming = List.generate(10, (index) {
      final date = today.add(Duration(days: index));
      return {
        'date': date,
        'dateFormatted': '${date.day} ${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][date.month - 1]} ${date.year}',
        'dayName': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][date.weekday - 1],
        'schemeId': 'INV-001',
        'schemeName': 'Gold Scheme A - Daily',
        'amount': 500,
        'status': 'UPCOMING',
        'installmentNumber': 26 + index,
      };
    });

    final paid = List.generate(30, (index) {
      final date = today.subtract(Duration(days: index + 1));
      return {
        'date': date,
        'dateFormatted': '${date.day} ${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][date.month - 1]} ${date.year}',
        'dayName': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][date.weekday - 1],
        'schemeId': 'INV-001',
        'schemeName': 'Gold Scheme A - Daily',
        'amount': 500,
        'status': index % 5 == 0 ? 'MISSED' : 'PAID',
        'installmentNumber': 25 - index,
        'receiptId': index % 5 == 0 ? null : 'RCP-2024-${(100000 + 25 - index).toString().padLeft(6, '0')}',
      };
    });

    return [...upcoming, ...paid];
  }

  // Expanded recent transactions
  static const List<Map<String, dynamic>> recentTransactions = [
    {'date': '25 Nov 2024', 'amount': 5000, 'status': 'PAID'},
    {'date': '24 Nov 2024', 'amount': 5000, 'status': 'PAID'},
    {'date': '23 Nov 2024', 'amount': 5000, 'status': 'MISSED'},
    {'date': '20 Nov 2024', 'amount': 5000, 'status': 'PAID'},
    {'date': '19 Nov 2024', 'amount': 5000, 'status': 'PAID'},
  ];

  // Total Investment Data
  static final Map<String, dynamic> totalInvestmentData = {
    'totalInvested': 100000,
    'currentValue': 125000,
    'totalGain': 25000,
    'gainPercent': 25.0,
    'assetBreakdown': [
      {
        'type': 'gold',
        'name': 'Gold Investments',
        'invested': 65000,
        'current': 72500,
        'gain': 7500,
        'gainPercent': 11.5,
      },
      {
        'type': 'silver',
        'name': 'Silver Investments',
        'invested': 35000,
        'current': 52500,
        'gain': 17500,
        'gainPercent': 50.0,
      },
    ],
    'activeSchemes': [
      {
        'id': 'INV-001',
        'name': 'Gold Scheme A',
        'invested': 50000,
        'current': 53000,
        'completedInstallments': 25,
        'totalInstallments': 200,
        'status': 'Active',
      },
      {
        'id': 'INV-002',
        'name': 'Silver Scheme B',
        'invested': 50000,
        'current': 72000,
        'completedInstallments': 12,
        'totalInstallments': 24,
        'status': 'Active',
      },
    ],
  };

  // All Transactions for Transaction History
  static final List<Map<String, dynamic>> allTransactions = [
    // November
    {'date': '2024-11-25', 'scheme': 'Gold Scheme A', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-001'},
    {'date': '2024-11-24', 'scheme': 'Gold Scheme A', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-002'},
    {'date': '2024-11-23', 'scheme': 'Gold Scheme A', 'amount': 5000, 'status': 'MISSED'},
    {'date': '2024-11-20', 'scheme': 'Silver Scheme B', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-003'},
    {'date': '2024-11-19', 'scheme': 'Silver Scheme B', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-004'},
    // October (sample)
    {'date': '2024-10-30', 'scheme': 'Gold Scheme A', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-005'},
    {'date': '2024-10-29', 'scheme': 'Gold Scheme A', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-006'},
    {'date': '2024-10-28', 'scheme': 'Silver Scheme B', 'amount': 5000, 'status': 'PAID', 'receiptId': 'RCP-007'},
  ];

  static final Map<String, dynamic> transactionSummary = {
    'totalPaid': 95000,
    'totalMissed': 5000,
    'totalTransactions': 25,
  };

  // Scheme Details
  static final Map<String, Map<String, dynamic>> schemeDetails = {
    // Gold Schemes 1-9
    'gold-scheme-1': {
      'id': 'gold-scheme-1',
      'name': 'Gold Scheme 1',
      'assetType': 'gold',
      'variantId': 'silver-scheme-1',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹50-200 daily for gold savings',
      'minDailyAmount': 50,
      'maxDailyAmount': 200,
      'installmentAmount': 125, // Average
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '500 mg',
      'entryFee': 100,
      'totalInvestment': 45625, // Average daily * 365
      'expectedGrams': 0.5,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹50-₹200)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 500 mg of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-2': {
      'id': 'gold-scheme-2',
      'name': 'Gold Scheme 2',
      'assetType': 'gold',
      'variantId': 'silver-scheme-2',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹250-500 daily for gold savings',
      'minDailyAmount': 250,
      'maxDailyAmount': 500,
      'installmentAmount': 375,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '1 g',
      'entryFee': 200,
      'totalInvestment': 136875,
      'expectedGrams': 1.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹250-₹500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 1 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-3': {
      'id': 'gold-scheme-3',
      'name': 'Gold Scheme 3',
      'assetType': 'gold',
      'variantId': 'silver-scheme-3',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹550-1,000 daily for gold savings',
      'minDailyAmount': 550,
      'maxDailyAmount': 1000,
      'installmentAmount': 775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '2 g',
      'entryFee': 300,
      'totalInvestment': 282875,
      'expectedGrams': 2.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹550-₹1,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 2 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-4': {
      'id': 'gold-scheme-4',
      'name': 'Gold Scheme 4',
      'assetType': 'gold',
      'variantId': 'silver-scheme-4',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹1,050-1,500 daily for gold savings',
      'minDailyAmount': 1050,
      'maxDailyAmount': 1500,
      'installmentAmount': 1275,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '3 g',
      'entryFee': 300,
      'totalInvestment': 465375,
      'expectedGrams': 3.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹1,050-₹1,500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 3 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-5': {
      'id': 'gold-scheme-5',
      'name': 'Gold Scheme 5',
      'assetType': 'gold',
      'variantId': 'silver-scheme-5',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹1,550-2,000 daily for gold savings',
      'minDailyAmount': 1550,
      'maxDailyAmount': 2000,
      'installmentAmount': 1775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '5 g',
      'entryFee': 300,
      'totalInvestment': 647875,
      'expectedGrams': 5.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹1,550-₹2,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 5 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-6': {
      'id': 'gold-scheme-6',
      'name': 'Gold Scheme 6',
      'assetType': 'gold',
      'variantId': 'silver-scheme-6',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹2,050-2,500 daily for gold savings',
      'minDailyAmount': 2050,
      'maxDailyAmount': 2500,
      'installmentAmount': 2275,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '5 g',
      'entryFee': 500,
      'totalInvestment': 830375,
      'expectedGrams': 5.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹2,050-₹2,500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 5 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-7': {
      'id': 'gold-scheme-7',
      'name': 'Gold Scheme 7',
      'assetType': 'gold',
      'variantId': 'silver-scheme-7',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹2,550-3,000 daily for gold savings',
      'minDailyAmount': 2550,
      'maxDailyAmount': 3000,
      'installmentAmount': 2775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '6 g',
      'entryFee': 500,
      'totalInvestment': 1012875,
      'expectedGrams': 6.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹2,550-₹3,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 6 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-8': {
      'id': 'gold-scheme-8',
      'name': 'Gold Scheme 8',
      'assetType': 'gold',
      'variantId': 'silver-scheme-8',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹3,100-3,900 daily for gold savings',
      'minDailyAmount': 3100,
      'maxDailyAmount': 3900,
      'installmentAmount': 3500,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '8 g',
      'entryFee': 500,
      'totalInvestment': 1277500,
      'expectedGrams': 8.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹3,100-₹3,900)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 8 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    'gold-scheme-9': {
      'id': 'gold-scheme-9',
      'name': 'Gold Scheme 9',
      'assetType': 'gold',
      'variantId': 'silver-scheme-9',
      'active': true,
      'icon': 'monetization_on',
      'tagline': 'Invest ₹3,950-5,000 daily for gold savings',
      'minDailyAmount': 3950,
      'maxDailyAmount': 5000,
      'installmentAmount': 4475,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '10 g',
      'entryFee': 500,
      'totalInvestment': 1633375,
      'expectedGrams': 10.0,
      'currentPrice': 6245,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Gold accumulation',
        'Higher returns',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹3,950-₹5,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 10 g of gold over 12 months',
        'Redeem as gold or cash on maturity',
      ],
    },
    // Silver Schemes 1-9
    'silver-scheme-1': {
      'id': 'silver-scheme-1',
      'name': 'Silver Scheme 1',
      'assetType': 'silver',
      'variantId': 'gold-scheme-1',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹50-200 daily for silver savings',
      'minDailyAmount': 50,
      'maxDailyAmount': 200,
      'installmentAmount': 125,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '25 g',
      'entryFee': 100,
      'totalInvestment': 45625,
      'expectedGrams': 25.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹50-₹200)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 25 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-2': {
      'id': 'silver-scheme-2',
      'name': 'Silver Scheme 2',
      'assetType': 'silver',
      'variantId': 'gold-scheme-2',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹250-500 daily for silver savings',
      'minDailyAmount': 250,
      'maxDailyAmount': 500,
      'installmentAmount': 375,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '50 g',
      'entryFee': 200,
      'totalInvestment': 136875,
      'expectedGrams': 50.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹250-₹500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 50 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-3': {
      'id': 'silver-scheme-3',
      'name': 'Silver Scheme 3',
      'assetType': 'silver',
      'variantId': 'gold-scheme-3',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹550-1,000 daily for silver savings',
      'minDailyAmount': 550,
      'maxDailyAmount': 1000,
      'installmentAmount': 775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '100 g',
      'entryFee': 300,
      'totalInvestment': 282875,
      'expectedGrams': 100.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹550-₹1,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 100 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-4': {
      'id': 'silver-scheme-4',
      'name': 'Silver Scheme 4',
      'assetType': 'silver',
      'variantId': 'gold-scheme-4',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹1,050-1,500 daily for silver savings',
      'minDailyAmount': 1050,
      'maxDailyAmount': 1500,
      'installmentAmount': 1275,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '150 g',
      'entryFee': 300,
      'totalInvestment': 465375,
      'expectedGrams': 150.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹1,050-₹1,500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 150 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-5': {
      'id': 'silver-scheme-5',
      'name': 'Silver Scheme 5',
      'assetType': 'silver',
      'variantId': 'gold-scheme-5',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹1,550-2,000 daily for silver savings',
      'minDailyAmount': 1550,
      'maxDailyAmount': 2000,
      'installmentAmount': 1775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '200 g',
      'entryFee': 300,
      'totalInvestment': 647875,
      'expectedGrams': 200.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹1,550-₹2,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 200 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-6': {
      'id': 'silver-scheme-6',
      'name': 'Silver Scheme 6',
      'assetType': 'silver',
      'variantId': 'gold-scheme-6',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹2,050-2,500 daily for silver savings',
      'minDailyAmount': 2050,
      'maxDailyAmount': 2500,
      'installmentAmount': 2275,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '250 g',
      'entryFee': 500,
      'totalInvestment': 830375,
      'expectedGrams': 250.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹2,050-₹2,500)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 250 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-7': {
      'id': 'silver-scheme-7',
      'name': 'Silver Scheme 7',
      'assetType': 'silver',
      'variantId': 'gold-scheme-7',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹2,550-3,000 daily for silver savings',
      'minDailyAmount': 2550,
      'maxDailyAmount': 3000,
      'installmentAmount': 2775,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '300 g',
      'entryFee': 500,
      'totalInvestment': 1012875,
      'expectedGrams': 300.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹2,550-₹3,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 300 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-8': {
      'id': 'silver-scheme-8',
      'name': 'Silver Scheme 8',
      'assetType': 'silver',
      'variantId': 'gold-scheme-8',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹3,100-3,900 daily for silver savings',
      'minDailyAmount': 3100,
      'maxDailyAmount': 3900,
      'installmentAmount': 3500,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '500 g',
      'entryFee': 500,
      'totalInvestment': 1277500,
      'expectedGrams': 500.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹3,100-₹3,900)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 500 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
    'silver-scheme-9': {
      'id': 'silver-scheme-9',
      'name': 'Silver Scheme 9',
      'assetType': 'silver',
      'variantId': 'gold-scheme-9',
      'active': true,
      'icon': 'account_balance_wallet',
      'tagline': 'Invest ₹3,950-5,000 daily for silver savings',
      'minDailyAmount': 3950,
      'maxDailyAmount': 5000,
      'installmentAmount': 4475,
      'frequency': 'daily',
      'duration': '12 months',
      'metalAccumulation': '550 g',
      'entryFee': 500,
      'totalInvestment': 1633375,
      'expectedGrams': 550.0,
      'currentPrice': 78,
      'features': [
        'Daily/Weekly/Monthly payments',
        'Silver accumulation',
        'Affordable entry',
        'Flexible payment options',
        'Secure investment',
        'Field staff collection service',
      ],
      'howItWorks': [
        'Choose your daily investment amount (₹3,950-₹5,000)',
        'Select payment frequency (Daily/Weekly/Monthly)',
        'Make payments on schedule',
        'Accumulate 550 g of silver over 12 months',
        'Redeem as silver or cash on maturity',
      ],
    },
  };
}
